## Default user and password
default_user = admin
default_pass = admin

## Allow the default user to connect from localhost
loopback_users.admin = false

## Set memory threshold to 0.4 of system memory
vm_memory_high_watermark.relative = 0.4

## Default vhost
default_vhost = /

## Enable management plugin
management.tcp.port = 15672

## Enable metrics
management.rates_mode = basic

## Configure queues
queue_master_locator = min-masters 