RABBITMQ_NODENAME=rabbit@localhost
RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
RABBITMQ_LOG_BASE=/var/log/rabbitmq
RABBITMQ_PLUGINS_EXPAND_DIR=/var/lib/rabbitmq/plugins
RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins 