input {
  tcp {
    port => 5000
    codec => json
  }
  udp {
    port => 5000
    codec => json
  }
  beats {
    port => 5044
  }
}

filter {
  if [type] == "auth-service" {
    mutate {
      add_field => { "[@metadata][service]" => "auth" }
    }
  }
  else if [type] == "user-service" {
    mutate {
      add_field => { "[@metadata][service]" => "user" }
    }
  }
  else if [type] == "game-service" {
    mutate {
      add_field => { "[@metadata][service]" => "game" }
    }
  }
  else if [type] == "chat-service" {
    mutate {
      add_field => { "[@metadata][service]" => "chat" }
    }
  }
  else if [type] == "notification-service" {
    mutate {
      add_field => { "[@metadata][service]" => "notification" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
} 