import { LanguageState } from "./languageStateTypes";

const en: LanguageState = {
  navbar: {
    play: "Play",
    oneV1local: "1v1 Local",
    oneV1remote: "Matchmaking",
    tournament: "Tournament",
    messages: "Messages",
    settings: "Settings",
    logout: "Logout",
  },
  register: {
    title: "Register",
    email: "Email",
    displayName: "Display Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    submit: "Register",
    alreadyRegistered: "Already registered?",
    testUsers: "Register Test_Users",
    passwordRuleMinLength: "Must be at least 8 characters long",
    passwordRuleMaxLength: "Must not exceed 256 characters",
    passwordRuleUppercase: "Must contain at least one uppercase letter",
    passwordRuleLowercase: "Must contain at least one lowercase letter",
    passwordRuleDigit: "Must contain at least one digit",
    passwordRuleSpecialChar: "Must contain at least one special character",
    errorPasswordMismatch: "Password does not match confirm password!",
    success: "Registered successfully! Redirecting to Login!",
    imageUpdateSuccess: "Profile picture updated successfully!",
    imageUpdateFail: "Couldn't update profile picture! Reason:",
    fileTooBig: "The file you chose is too big! Please select a file smaller than 4 MB!",
    invalidFileFormat: "Only files with extensions 'jpg' or 'png' are supported!",

},

  matchMaking: {
    publicMatches: "Public Matches",
    privateMatches: "Private Matches",
    tournamentMatches: "Tournament Matches",
    yourOwnMatchHeading: "Your own match",
    createMatch: "Create Match",
    closeMatchButton: "Close Match",
    join: "Join",
    match: "Match",
    matchMaking: "Matchmaking",
    noMatchesAvailable: "No matches available!",
    yourMatch: "Your match",
    tournaments: "Tournaments",
    createTournament: "Create Tournament",
  },
  oneVOneLocal: {
    player1: "Player 1",
    player2: "Player 2",
    startGame: "Start Game",
    localGameOnSame: "Local game on same keyboard",
    aIOrHumanBtnHuman: "Human Opponent",
    aIOrHumanBtnAi: "AI Opponent",
  },
  manageMatch: {
  waitingServerStart: "Waiting for the server to start...",
  cancelKeyInstruction: "Press 'n' to cancel the game",
  readyKeyInstruction: "Press 'y' when you are ready",
  },
  currentTournament: {
    title: "Tournament Overview",
    rankings: "Player Rankings",
    rank: "Rank",
    name: "Name",
    getDataBtn: "Fetch data via API",
    toBeDetermined: "To be determined",
    player1: "Player 1",
    player2: "Player 2",
    result: "Result",
    winner: "Winner",
    createGame: "Create Game",
    waitingForHost: "Waiting for the host",
    notParticipant: "This is not your match!",
  },
  tournamentItem: {
    tournamentId: "Tournament ID",
    player1: "Player 1",
    player2: "Player 2",
    player3: "Player 3",
    player4: "Player 4",
    join: "Join",
    leave: "Leave",
    freeSpot: ">free<",
  },
  matchItem: {
    matchId: "Match ID",
    gameOf: "Game of",
    waitingForOpponent: "Waiting for an opponent!",
    typeOfGame: "Game Type",
    join: "Join",
    gameRunning: "Game in progress",
  },
  userSettings: {
    userSettings: "User Settings",
    displayName: "Display Name",
    email: "Email",
    save: "Save",
    password: "Password",
  },
  chat: {
    tabs: {
      users: "Users",
      blocked: "Blocked",
      friendRequests: "Friend Requests",
    },
    sections: {
      friends: "Friends",
      online: "Online",
      offline: "Offline",
      blockedUsers: "Blocked Users",
      answerRequired: "Answer Required",
      ownPending: "Own Pending",
    },
    buttons: {
      sendMessage: "Send Message",
      blockUser: "Block User",
      unblockUser: "Unblock User",
      acceptRequest: "Accept",
      declineRequest: "Decline",
      withdrawRequest: "Withdraw Request",
      pending: "Pending",
    },
    placeholders: {
      searchUsers: "Search users...",
      typeMessage: "Type your message here...",
    },
    notifications: {
      userBlocked: "User blocked successfully.",
      userUnblocked: "User unblocked successfully.",
      friendRequestAccepted: "Friend request accepted.",
      friendRequestDeclined: "Friend request declined.",
    }
  }
} as const;

export { en };
