import { LanguageState } from "./languageStateTypes";
const fr: LanguageState = {
  navbar: {
    play: "Jouer",
    oneV1local: "1v1 Local",
    oneV1remote: "Matchmaking",
    tournament: "Tournoi",
    messages: "Messages",
    settings: "Paramètres",
    logout: "Déconnexion",
  },
  matchMaking: {
    publicMatches: "Matchs publics",
    privateMatches: "Matchs privés",
    tournamentMatches: "Matchs de tournoi",
    yourOwnMatchHeading: "Votre propre match",
    createMatch: "Créer un match",
    closeMatchButton: "Fermer le match",
    join: "Rejoindre",
    match: "Match",
    matchMaking: "Matchmaking",
    noMatchesAvailable: "Aucun match disponible !",
    yourMatch: "Votre match",
    tournaments: "Tournois",
    createTournament: "Créer un tournoi",
  },
  manageMatch: {
    waitingServerStart: "En attente du démarrage du serveur...",
    cancelKeyInstruction: "Appuyez sur 'n' pour annuler la partie",
    readyKeyInstruction: "Appuyez sur 'y' quand vous êtes prêt.e",
  },
  currentTournament: {
    title: "Aperçu du Tournoi",
    rankings: "Classement des Joueurs",
    rank: "Rang",
    name: "Nom",
    getDataBtn: "Récupérer les données via l'API",
    toBeDetermined: "À déterminer",
    player1: "Joueur·euse 1",
    player2: "Joueur·euse 2",
    result: "Résultat",
    winner: "Vainqueur",
    createGame: "Créer la Partie",
    waitingForHost: "En attente de l’hôte",
    notParticipant: "Ce n’est pas votre match !",
  },
  oneVOneLocal: {
    player1: "Joueur·euse 1",
    player2: "Joueur·euse 2",
    startGame: "Démarrer la partie",
    localGameOnSame: "Partie locale sur le même clavier",
    aIOrHumanBtnHuman: "Adversaire humain",
    aIOrHumanBtnAi: "Adversaire IA",
    enterPlayer2NamePlaceholder: "Entrez le nom du·de la joueur·euse 2",
  },
  userSettings: {
    userSettings: "Paramètres utilisateur·rice",
    displayName: "Nom affiché",
    email: "E-mail",
    save: "Enregistrer",
    password: "Mot de passe",
    matchHistoryCaption: "Historique des matchs",
    oponent: "Adversaire",
    loss: "Défaite",
    win: "Victoire",
    tournamentHistoryCaption: "Historique du tournoi",
    ranking: "Classement",
    semifinale: "Demi-finale",
    bronzeMatch: "Match pour la 3ᵉ place",
    finale: "Finale",
    score: "Score",
    first: "1er",
    second: "2e",
    third: "3e",
    fourth: "4e",
    statsCaption: "Statistiques",
    wins: "Victoires",
    losses: "Défaites",
    winPercentage: "Pourcentage de victoires",
    lossPercentage: "Pourcentage de défaites",
  },
  tournamentItem: {
    tournamentId: "ID du tournoi",
    player1: "Joueur·euse 1",
    player2: "Joueur·euse 2",
    player3: "Joueur·euse 3",
    player4: "Joueur·euse 4",
    join: "Rejoindre",
    leave: "Quitter",
    freeSpot: ">libre<",
  },
  matchItem: {
    matchId: "ID du match",
    gameOf: "Partie de",
    waitingForOpponent: "En attente d'un·e adversaire !",
    typeOfGame: "Type de partie",
    join: "Rejoindre",
    gameRunning: "Partie en cours",
  },
  register: {
    title: "Inscription",
    email: "E‑mail",
    displayName: "Nom affiché",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    submit: "S'inscrire",
    submitLogin: "Se connecter",
    notregistered: "Pas encore de compte? S'inscrire",
    alreadyRegistered: "Déjà inscrit·e ? Se connecter",
    testUsers: "Connexion en tant que test_user_{n}",
    passwordRuleMinLength: "Doit comporter au moins 8 caractères",
    passwordRuleMaxLength: "Ne doit pas dépasser 256 caractères",
    passwordRuleUppercase: "Doit contenir au moins une lettre majuscule",
    passwordRuleLowercase: "Doit contenir au moins une lettre minuscule",
    passwordRuleDigit: "Doit contenir au moins un chiffre",
    passwordRuleSpecialChar: "Doit contenir au moins un caractère spécial",
    errorPasswordMismatch:
      "Le mot de passe ne correspond pas à la confirmation !",
    success: "Inscription réussie ! Redirection vers la page de connexion...",
    save: "Enregistrer",
    reset: "Réinitialiser",
    matchHistory: "Historique des matchs",
    friends: "Amis",
    profilePicture: "Photo de profil",
    imageUpdateSuccess: "Photo de profil mise à jour avec succès !",
    imageUpdateFail: "Erreur de mise à jour de la photo : ",
    fileTooBig:
      "Le fichier est trop volumineux ! Veuillez sélectionner un fichier inférieur à 4 Mo.",
    invalidFileFormat:
      "Seuls les fichiers de format 'jpg' ou 'png' sont supportés !",
    emailUpdateSuccess: "E‑mail mis à jour avec succès !",
    emailUpdateFail: "Erreur lors de la mise à jour de l'e‑mail : ",
    passwordUpdateSuccess: "Mot de passe mis à jour avec succès !",
    passwordUpdateFail: "Erreur lors de la mise à jour du mot de passe : ",
    displayNameUpdateSuccess: "Nom d'affichage mis à jour avec succès !",
    displayNameUpdateFail:
      "Erreur lors de la mise à jour du nom d'affichage : ",
    clickToChangeProfilePicture: "Cliquez pour changer la photo de profil",
    tournament: "Tournoi",
  },

  chat: {
    tabs: {
      users: "Utilisateur·rice ",
      blocked: "Bloqué·es",
      friendRequests: "Demandes d'amis",
    },
    sections: {
      notifierBots: "Notifications",
      friends: "Ami·es",
      online: "En ligne",
      offline: "Hors ligne",
      blockedUsers: "Utilisateur·rices  bloqué·es",
      answerRequired: "Réponse requise",
      ownPending: "En attente",
    },
    buttons: {
      sendMessage: "Envoyer un message",
      blockUser: "Bloquer l'utilisateur·rice",
      unblockUser: "Débloquer l'utilisateur·rice",
      acceptRequest: "Accepter",
      declineRequest: "Refuser",
      withdrawRequest: "Retirer la demande",
      pending: "En attente",
      goToGameArea: "Aller à l'aire de jeu",
    },
    placeholders: {
      searchUsers: "Rechercher des utilisateur·rice...",
      typeMessage: "Tapez votre message ici...",
    },
    notifications: {
      userBlocked: "utilisateur·rice  bloqué·e avec succès.",
      userUnblocked: "utilisateur·rice  débloqué·e avec succès.",
      friendRequestAccepted: "Demande d'ami acceptée.",
      friendRequestDeclined: "Demande d'ami refusée.",
      invite: "L'utilisateur vous a invité à jouer une partie avec lui\nCliquez ici pour rejoindre.",
    }
  },
} as const;

export { fr };
