import { LanguageState } from "./languageStateTypes";
const fr: LanguageState = {
  navbar: {
    play: "Jouer",
    oneV1local: "1v1 Local",
    oneV1remote: "Matchmaking",
    tournament: "Tournoi",
    messages: "Messages",
    settings: "Paramètres",
    logout: "Déconnexion",
  },
  matchMaking: {
    publicMatches: "Matchs publics",
    privateMatches: "Matchs privés",
    tournamentMatches: "Matchs de tournoi",
    yourOwnMatchHeading: "Votre propre match",
    createMatch: "Créer un match",
    closeMatchButton: "Fermer le match",
    join: "Rejoindre",
    match: "Match",
    matchMaking: "Matchmaking",
    noMatchesAvailable: "Aucun match disponible !",
    yourMatch: "Votre match",
    tournaments: "Tournois",
    createTournament: "Créer un tournoi",
  },
  manageMatch: {
    waitingServerStart: "En attente du démarrage du serveur...",
    cancelKeyInstruction: "Appuyez sur 'n' pour annuler la partie",
    readyKeyInstruction: "Appuyez sur 'y' quand vous êtes prêt.e",
  },
  currentTournament: {
  title: "Aperçu du Tournoi",
  rankings: "Classement des Joueurs",
  rank: "Rang",
  name: "Nom",
  getDataBtn: "Récupérer les données via l'API",
  toBeDetermined: "À déterminer",
  player1: "Joueur·euse 1",
  player2: "Joueur·euse 2",
  result: "Résultat",
  winner: "Vainqueur",
  createGame: "Créer la Partie",
  waitingForHost: "En attente de l’hôte",
  notParticipant: "Ce n’est pas votre match !"
  },
  oneVOneLocal: {
    player1: "Joueur·euse 1",
    player2: "Joueur·euse 2",
    startGame: "Démarrer la partie",
    localGameOnSame: "Partie locale sur le même clavier",
    aIOrHumanBtnHuman: "Adversaire humain",
    aIOrHumanBtnAi: "Adversaire IA",
  },
  userSettings: {
    userSettings: "Paramètres utilisateur·rice",
    displayName: "Nom affiché",
    email: "E-mail",
    save: "Enregistrer",
    password: "Mot de passe",
  },
    tournamentItem: {
    tournamentId: "ID du tournoi",
    player1: "Joueur·euse 1",
    player2: "Joueur·euse 2",
    player3: "Joueur·euse 3",
    player4: "Joueur·euse 4",
    join: "Rejoindre",
    leave: "Quitter",
    freeSpot: ">libre<",
  },
    matchItem: {
    matchId: "ID du match",
    gameOf: "Partie de",
    waitingForOpponent: "En attente d'un·e adversaire !",
    typeOfGame: "Type de partie",
    join: "Rejoindre",
    gameRunning: "Partie en cours",
  },
  chat: {
    tabs: {
      users: "Utilisateur·rice ",
      blocked: "Bloqué·es",
      friendRequests: "Demandes d'amis",
    },
    sections: {
      friends: "Ami·es",
      online: "En ligne",
      offline: "Hors ligne",
      blockedUsers: "utilisateur·rices  bloqué·es",
      answerRequired: "Réponse requise",
      ownPending: "En attente",
    },
    buttons: {
      sendMessage: "Envoyer un message",
      blockUser: "Bloquer l'utilisateur·rice",
      unblockUser: "Débloquer l'utilisateur·rice",
      acceptRequest: "Accepter",
      declineRequest: "Refuser",
	  withdrawRequest: "Retirer la demande",
	  pending: "En attente",
    },
    placeholders: {
      searchUsers: "Rechercher des utilisateur·rice ...",
      typeMessage: "Tapez votre message ici...",
    },
    notifications: {
      userBlocked: "utilisateur·rice  bloqué·e avec succès.",
      userUnblocked: "utilisateur·rice  débloqué·e avec succès.",
      friendRequestAccepted: "Demande d'ami acceptée.",
      friendRequestDeclined: "Demande d'ami refusée.",
    }
  },
} as const;

export { fr };
